import Head from "next/head";
import Image from "next/image";
import {
  Heading,
  Text,
  Box,
  Tooltip,
  Container,
  Stack,
  HStack,
  VStack,
  Stat,
  StatLabel,
  StatNumber,
  StatHelpText,
  StatArrow,
  StatGroup,
  Radio,
  RadioGroup,
} from "@chakra-ui/react";
import data from "../collections.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BSC NFT Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.md">
        <Stack spacing={4}>
          <Box mt={12} pb={8} borderRadius="lg" borderWidth={"1px"} p="4">
            <Heading as="h1" size="xl">
              BSC NFT Explorer
            </Heading>
            <Text color="gray.500" mt={4}>
              Explore NFTs and key NFT metrics on Binance Smart chain
            </Text>
          </Box>
          <Box borderRadius="lg" borderWidth={"1px"} p="4"></Box>
          <Box borderRadius="lg" borderWidth={"1px"} p="4">
            <StatGroup>
              <Stat>
                <StatLabel>h Volume</StatLabel>
                <StatNumber></StatNumber>
                <StatHelpText>
                  <StatArrow type={"increase"} />%
                </StatHelpText>
              </Stat>
            </StatGroup>
          </Box>
          <Box borderRadius="lg" borderWidth={"1px"} p="4">
            <Heading as="h2" size="sm" mb={3}>
              Collections
            </Heading>
          </Box>
          <Box borderRadius="lg" borderWidth={"1px"} p="4">
            <Heading as="h2" size="sm" mb={3}>
              Top collections by volume
            </Heading>
          </Box>
        </Stack>
      </Container>
    </div>
  );
}

// export async function getServerSideProps({ params }) {
//   const res = await fetch(`https://...`);
//   const data = await res.json();

//   if (!data) {
//     return {
//       notFound: true,
//     };
//   }

//   return {
//     props: {}, // will be passed to the page component as props
//   };
// }
